

CREATE TABLE public."/tb_item_pedido" (
    preco double precision,
    quantidade integer,
    produto_id bigint NOT NULL,
    pedido_id bigint NOT NULL
);


--
-- Name: tb_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_categoria (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_pagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_pagamento (
    momento timestamp(6) with time zone,
    pedido_id bigint NOT NULL
);


--
-- Name: tb_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_pedido (
    id bigint NOT NULL,
    momento timestamp(6) with time zone,
    pedido_status integer,
    client_id bigint
);


--
-- Name: tb_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_produto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_produto (
    id bigint NOT NULL,
    descricao character varying(255),
    img_url character varying(255),
    nome character varying(255),
    preco double precision
);


--
-- Name: tb_produto_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_produto_categoria (
    produto_id bigint NOT NULL,
    categoria_id bigint NOT NULL
);


--
-- Name: tb_produto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    email character varying(255),
    endereco character varying(255),
    nome character varying(255),
    senha character varying(255),
    telefone character varying(255)
);


--
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: /tb_item_pedido /tb_item_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."/tb_item_pedido"
    ADD CONSTRAINT "/tb_item_pedido_pkey" PRIMARY KEY (pedido_id, produto_id);


--
-- Name: tb_categoria tb_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_categoria
    ADD CONSTRAINT tb_categoria_pkey PRIMARY KEY (id);


--
-- Name: tb_pagamento tb_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_pagamento
    ADD CONSTRAINT tb_pagamento_pkey PRIMARY KEY (pedido_id);


--
-- Name: tb_pedido tb_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_pedido
    ADD CONSTRAINT tb_pedido_pkey PRIMARY KEY (id);


--
-- Name: tb_produto_categoria tb_produto_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_produto_categoria
    ADD CONSTRAINT tb_produto_categoria_pkey PRIMARY KEY (produto_id, categoria_id);


--
-- Name: tb_produto tb_produto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_produto
    ADD CONSTRAINT tb_produto_pkey PRIMARY KEY (id);


--
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- Name: tb_produto_categoria fk3becm1bka4cpmorcubx1fxl02; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_produto_categoria
    ADD CONSTRAINT fk3becm1bka4cpmorcubx1fxl02 FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id);


--
-- Name: /tb_item_pedido fk6lm1b24xhusac1pth3bpu08mx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."/tb_item_pedido"
    ADD CONSTRAINT fk6lm1b24xhusac1pth3bpu08mx FOREIGN KEY (produto_id) REFERENCES public.tb_produto(id);


--
-- Name: tb_produto_categoria fk98jyjls8tavr9o4wur6g9780c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_produto_categoria
    ADD CONSTRAINT fk98jyjls8tavr9o4wur6g9780c FOREIGN KEY (produto_id) REFERENCES public.tb_produto(id);


--
-- Name: /tb_item_pedido fkbojh8i1v1tmb5yhyqd4yj4ic5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."/tb_item_pedido"
    ADD CONSTRAINT fkbojh8i1v1tmb5yhyqd4yj4ic5 FOREIGN KEY (pedido_id) REFERENCES public.tb_pedido(id);


--
-- Name: tb_pedido fkgglbsqfsjs4h4ab1hf65e8fsm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_pedido
    ADD CONSTRAINT fkgglbsqfsjs4h4ab1hf65e8fsm FOREIGN KEY (client_id) REFERENCES public.tb_user(id);


--
-- Name: tb_pagamento fkjghfnncmma1w9wn5hnpq6nhx2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_pagamento
    ADD CONSTRAINT fkjghfnncmma1w9wn5hnpq6nhx2 FOREIGN KEY (pedido_id) REFERENCES public.tb_pedido(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Fbhf426oI1vJMAoUg1KvAv6FnFHDpatAlQg6TC3fCyEpX9ONuZLgufzWAYCJMZt

